# Oracle DB connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=CLIENTE
spring.datasource.password=Cliente1234!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=8081

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
