-- RIPRISTINO GUIDATO DEL DATABASE DEMO
--
-- Database configurato attualmente: Oracle XE nel container oracle-demo,
-- host localhost, porta 1521, service name XEPDB1.
--
-- 1) Da CMD, nella cartella C:\projects\oracle-crud-demo, avviare Oracle:
--      docker compose up -d oracle
--      docker logs -f oracle-demo
--    Attendere "DATABASE IS READY TO USE!", poi Ctrl+C per uscire dai log.
--
-- 2) Entrare come amministratore:
--      docker exec -it oracle-demo sqlplus system/demo_pass@XEPDB1
--
-- 3) Da DBeaver, collegarsi come SYSTEM a localhost:1521/XEPDB1, aprire
--    questo file e scegliere "Esegui script" (non "Esegui istruzione").
--
-- Lo script crea CLIENTE e CLIENTE.CLIENTE se non esistono, reimposta sempre
-- la password CLIENTE a Cliente1234! e non elimina righe o tabelle esistenti.
-- Deve essere eseguito come SYSTEM o altro utente DBA sul PDB XEPDB1.

SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON
SET VERIFY OFF

PROMPT === 1. Verifica database, PDB e utente connesso ===
SHOW USER
SELECT SYS_CONTEXT('USERENV', 'DB_NAME') AS database_name,
       SYS_CONTEXT('USERENV', 'CON_NAME') AS pdb_name,
       SYS_CONTEXT('USERENV', 'SERVICE_NAME') AS service_name
  FROM dual;

PROMPT === 2. Crea l'utente CLIENTE se manca ===
DECLARE
  v_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM dba_users
   WHERE username = 'CLIENTE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER CLIENTE IDENTIFIED BY "Cliente1234!"';
    DBMS_OUTPUT.PUT_LINE('Creato CLIENTE.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('CLIENTE esiste già.');
  END IF;
END;
/

PROMPT === 3. Imposta password e privilegi applicativi ===
ALTER USER CLIENTE IDENTIFIED BY "Cliente1234!" ACCOUNT UNLOCK;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO CLIENTE;
ALTER USER CLIENTE QUOTA UNLIMITED ON USERS;

PROMPT === 4. Crea la tabella CLIENTE.CLIENTE se manca ===
DECLARE
  v_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM dba_tables
   WHERE owner = 'CLIENTE'
     AND table_name = 'CLIENTE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE CLIENTE.CLIENTE (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome VARCHAR2(50) NOT NULL,
      cognome VARCHAR2(50) NOT NULL,
      email VARCHAR2(100),
      telefono VARCHAR2(20)
    )~';
    DBMS_OUTPUT.PUT_LINE('Creata CLIENTE.CLIENTE.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('CLIENTE.CLIENTE esiste già; dati e struttura lasciati invariati.');
  END IF;
END;
/

PROMPT === 5. Verifica stato utente ===
SELECT username, account_status, default_tablespace
  FROM dba_users
 WHERE username = 'CLIENTE';

PROMPT === 6. Verifica tabella e colonne ===
SELECT owner, table_name, tablespace_name
  FROM dba_tables
 WHERE owner = 'CLIENTE'
   AND table_name = 'CLIENTE';

SELECT column_id, column_name, data_type, data_length, nullable, identity_column
  FROM dba_tab_columns
 WHERE owner = 'CLIENTE'
   AND table_name = 'CLIENTE'
 ORDER BY column_id;

PROMPT === 7. Credenziali e connessione DBeaver per l'applicazione ===
PROMPT Host localhost, porta 1521, Service name XEPDB1
PROMPT Username CLIENTE, password Cliente1234!
PROMPT JDBC: jdbc:oracle:thin:@localhost:1521/XEPDB1
PROMPT Collegarsi come CLIENTE e verificare con: SELECT COUNT(*) FROM CLIENTE;

SET ECHO OFF
