-- 01_schema.sql
-- Run while connected to FREEPDB1 as SYSTEM (or another DBA user).
CREATE USER CLIENTE IDENTIFIED BY oracle;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO CLIENTE;
ALTER USER CLIENTE QUOTA UNLIMITED ON USERS;
