-- 02_tables.sql
-- Run after connecting as CLIENTE to FREEPDB1.
CREATE TABLE cliente (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL,
    cognome VARCHAR2(50) NOT NULL,
    email VARCHAR2(100),
    telefono VARCHAR2(20)
);
